name: Pull Request
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  call-quality-check:
    uses: ./.github/workflows/quality_check.yml