name: Quality check
on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.coverage.outputs.percentage }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependencies
        run: go mod tidy
      - name: Check if build
        run: go build ./cmd/api
      - name: Run tests with coverage
        run: |
          go test ./... -coverprofile=coverage
          go tool cover -func=coverage | grep total | 'percentage=$(awk {print $3})' >> $GITHUB_OUTPUT ';'
        id: coverage
      - name: Validate coverage
        run: |
          echo "Coverage output:"
          echo "${{ steps.coverage.outputs.percentage }}"
          COVERAGE=$(echo "${{ steps.coverage.outputs.percentage }}" | awk '{print $3}')
          echo "Coverage value:"
          echo "$COVERAGE"
          if (( $(echo "$COVERAGE < 50" | bc -l) )); then
            echo "Test coverage is below 50%"
            exit 1
          fi