name: Quality check
on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependencies
        run: go mod tidy
      - name: Check if build
        run: go build ./cmd/api
      - name: Go vet
        run: go vet ./...
      - name: Go fmt
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            gofmt -s -l .
            echo "Please format Go code by running: go fmt ./..."
            exit 1 
          fi
      - name: Run tests with coverage
        id: coverage
        run: |
          go test ./... -coverprofile=coverage
          echo "percentage=$(go tool cover -func=coverage | grep total | awk '{print $3}')" >> $GITHUB_OUTPUT
      - name: Validate coverage
        run: |
          if [[ ${{ steps.coverage.outputs.percentage }} < 70 ]]; then
            echo "Test coverage is below 70%"
            exit 1
          fi
